name: ahianeo-db

services:
  postgres:
    image: postgres:17.5
    container_name: ahianeo-pg
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ahianeo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: